### PR TITLE
added

### PR DESCRIPTION
**Pull request by Jyotika999**

### CODE REVIEW

**Comment by Jyotika999** [comment]
Updated the README file. 
Suggestions requested.

**Review by Tlazypanda — COMMENTED** [review]
Hey @Jyotika999 can you add some information about Elevate Labs and how we as a student organisation are building projects that can solve community problems since this template repo readme will be inherited in every repo so having some Info about our initiative can help a lot :smile:

**Comment by Tlazypanda** [comment]
Also Jyotika since you are contributing to Open source some Info in the issue description about the change and fixes #1 can really help the maintainers!! ✌️

**Comment by Freebird999** [comment]
Okay Mam,  I will work upon it.

**Comment by Jyotika999** [comment]
Okay mam, I will work upon it.

**Comment by Tlazypanda** [comment]
Hey @Jyotika999 I didn't close this since I wanted you to make a contribution :p I know the readme has been updated with some stuff doesn't mean that we can't have more contributions :v:

**Comment by Jyotika999** [comment]
Sure, Mam, I will do the necessary changes and make a new PR for the same.

**Pull request closed without merging**
